### ISSUE TITLE
Add a page title

### ISSUE THREAD

**Issue by its-me-anoop** [its-me-anoop/its-me-anoop.github.io#1]

**Comment by Yasshu55** [comment]
i want to work on this particular issue can you please assign it to me?

**Comment by Vaishnavi1217** [comment]
I want to work on this issue! Can you please Assign this issue to me

**Comment by Alekhya193** [comment]
i want to work on this issue plz assign this issue to me

**Comment by Maahi10001** [comment]
basically is adding a page title which is quite simple and i can do to as easy and good ,so can you assign the issue.

**Comment by KhushbooChaudhari10** [comment]
i want to work on this issue plz assign this issue to me
